# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  repositories:
    apt:
      repo: 'https://github.com/puppetlabs/puppetlabs-apt.git'
      ref: 'v7.4.1'
    concat:
      repo: 'https://github.com/puppetlabs/puppetlabs-concat.git'
      ref: 'v6.2.0'
    cron_core:
      repo: "https://github.com/puppetlabs/puppetlabs-cron_core.git"
      ref: "1.0.3"
      puppet_version: ">= 6.0.0"
    facts:
      repo: 'https://github.com/puppetlabs/puppetlabs-facts.git'
      ref: '1.0.0'
    firewall:
      repo: 'https://github.com/puppetlabs/puppetlabs-firewall.git'
      ref: 'v2.3.0'
    git:
      repo: 'https://github.com/puppetlabs/puppetlabs-git.git'
      ref: '0.5.0'
    hiera:
      repo: 'https://github.com/voxpupuli/puppet-hiera.git'
      ref: 'v4.0.0'
    inifile:
      repo: 'https://github.com/puppetlabs/puppetlabs-inifile.git'
      ref: 'v4.1.0'
    postgresql:
      repo: 'https://github.com/puppetlabs/puppetlabs-postgresql.git'
      ref: 'v6.4.0'
    provision:
      repo: 'https://github.com/puppetlabs/provision.git'
      ref: '3b21c3208807caafa853ff06c9d940d2057a0e04'
    puppet_agent:
      repo: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
      ref: '3.1.0'
    puppetdb:
      repo: 'https://github.com/puppetlabs/puppetlabs-puppetdb.git'
      ref: '7.4.0'
    puppetserver_gem:
      repo: 'https://github.com/puppetlabs/puppetlabs-puppetserver_gem.git'
      ref: '1.1.1'
    ruby:
      repo: 'https://github.com/puppetlabs/puppetlabs-ruby.git'
      ref: 'v1.0.1'
    r10k:
      repo: 'https://github.com/voxpupuli/puppet-r10k.git'
      ref: 'v8.2.0'
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: 'v6.3.0'
    translate:
      repo: 'https://github.com/puppetlabs/puppetlabs-translate.git'
      ref: 'v2.2.0'
    vcsrepo:
      repo: 'https://github.com/puppetlabs/puppetlabs-vcsrepo.git'
      ref: 'v3.1.0'
  symlinks:
    profile: "#{source_dir}"
