# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  repositories:
    accounts:
      repo: 'https://github.com/puppetlabs/puppetlabs-accounts.git'
      ref: 'v6.1.1'
    alternative:
      repo: 'https://github.com/voxpupuli/puppet-alternatives.git'
      ref: 'v3.0.0'
    apt:
      repo: 'https://github.com/puppetlabs/puppetlabs-apt.git'
      ref: 'v7.4.1'
    archive:
      repo: 'https://github.com/voxpupuli/puppet-archive.git'
      ref: 'v4.5.0'
    augeas:
      repo: 'https://github.com/camptocamp/puppet-augeas.git'
      ref: '1.9.0'
    augeas_core:
      repo: 'https://github.com/puppetlabs/puppetlabs-augeas_core.git'
      ref: '1.0.5'
    augeasproviders_core:
      repo: 'https://github.com/hercules-team/augeasproviders_core'
      ref: '2.6.0'
    bareos:
      repo: 'https://github.com/Project0/puppet-bareos.git'
      ref: '973928680d7ab720c873fcdc1d4c950299fdff91'
    concat:
      repo: 'https://github.com/puppetlabs/puppetlabs-concat.git'
      ref: 'v6.2.0'
    cron_core:
      repo: "https://github.com/puppetlabs/puppetlabs-cron_core.git"
      ref: "1.0.3"
      puppet_version: ">= 6.0.0"
    facts:
      repo: 'https://github.com/puppetlabs/puppetlabs-facts.git'
      ref: '1.0.0'
    firewall:
      repo: 'https://github.com/puppetlabs/puppetlabs-firewall.git'
      ref: 'v2.3.0'
    gernox_bareos:
      repo: 'https://github.com/gernox/puppet-bareos.git'
      ref: 'origin/production'
    gernox_keycloak:
      repo: 'https://github.com/gernox/puppet-keycloak.git'
      ref: 'origin/production'
    git:
      repo: 'https://github.com/puppetlabs/puppetlabs-git.git'
      ref: '0.5.0'
    grafana:
      repo: 'https://github.com/voxpupuli/puppet-grafana.git'
      ref: 'v6.1.0'
    healthcheck:
      repo: 'https://github.com/voxpupuli/puppet-healthcheck.git'
      ref: 'v1.0.1'
    hiera:
      repo: 'https://github.com/voxpupuli/puppet-hiera.git'
      ref: 'v4.0.0'
    host_core:
      repo: 'https://github.com/puppetlabs/puppetlabs-host_core.git'
      ref: '1.0.3'
    inifile:
      repo: 'https://github.com/puppetlabs/puppetlabs-inifile.git'
      ref: 'v4.1.0'
    letsencrypt:
      repo: 'https://github.com/voxpupuli/puppet-letsencrypt.git'
      ref: 'v5.0.0'
    mailalias_core:
      repo: 'https://github.com/puppetlabs/puppetlabs-mailalias_core.git'
      ref: '1.0.6'
    nginx:
      repo: 'https://github.com/voxpupuli/puppet-nginx.git'
      ref: '845d06f4388480e2d4a73948dcbb99be7766cfc4'
    noop:
      repo: 'https://github.com/trlinkin/trlinkin-noop.git'
      ref: '1.0.1'
    ntp:
      repo: 'https://github.com/puppetlabs/puppetlabs-ntp.git'
      ref: 'v8.3.0'
    ohmyzsh:
      repo: 'https://github.com/rehanone/puppet-ohmyzsh.git'
      ref: '2.3.2'
    php:
      repo: 'https://github.com/voxpupuli/puppet-php.git'
      ref: 'v7.1.0'
    postfix:
      repo: 'https://github.com/camptocamp/puppet-postfix.git'
      ref: '1.10.0'
    postgresql:
      repo: 'https://github.com/puppetlabs/puppetlabs-postgresql.git'
      ref: 'v6.5.0'
    prometheus:
      repo: 'https://github.com/voxpupuli/puppet-prometheus.git'
      ref: 'v8.4.0'
    provision:
      repo: 'https://github.com/puppetlabs/provision.git'
      ref: '3b21c3208807caafa853ff06c9d940d2057a0e04'
    puppet_agent:
      repo: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
      ref: '3.1.0'
    puppetdb:
      repo: 'https://github.com/puppetlabs/puppetlabs-puppetdb.git'
      ref: '7.4.0'
    puppetserver_gem:
      repo: 'https://github.com/puppetlabs/puppetlabs-puppetserver_gem.git'
      ref: '1.1.1'
    ruby:
      repo: 'https://github.com/puppetlabs/puppetlabs-ruby.git'
      ref: 'v1.0.1'
    r10k:
      repo: 'https://github.com/voxpupuli/puppet-r10k.git'
      ref: 'v8.2.0'
    ssh:
      repo: 'https://github.com/saz/puppet-ssh.git'
      ref: 'v6.1.0'
    sshkeys:
      repo: 'https://github.com/puppetlabs/puppetlabs-sshkeys_core'
      ref: '2.0.0'
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: 'v6.3.0'
    sysctl:
      repo: 'https://github.com/hercules-team/augeasproviders_sysctl'
      ref: '2.5.0'
    systemd:
      repo: 'https://github.com/camptocamp/puppet-systemd.git'
      ref: '2.9.0'
    translate:
      repo: 'https://github.com/puppetlabs/puppetlabs-translate.git'
      ref: 'v2.2.0'
    vcsrepo:
      repo: 'https://github.com/puppetlabs/puppetlabs-vcsrepo.git'
      ref: 'v3.1.0'
    vim:
      repo: 'https://github.com/saz/puppet-vim'
      ref: 'v2.7.0'
    wireguard:
      repo: 'https://github.com/spacedog/puppet-wireguard.git'
      ref: 'v0.4.2'
  symlinks:
    profile: "#{source_dir}"
